name: xaitools
channels:
  - defaults
dependencies:
  - _libgcc_mutex
  - ca-certificates=2021.1.19
  - ncurses=6.2
  - openssl=1.1.1k
  - pip>=21.0.0
  - python>=3.6
  - readline=8.1
  - setuptools=52.0.0
  - sqlite=3.35.2
  - tk=8.6.10
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - attrs>=20.3.0
    - backcall>=0.2.0
    - cloudpickle>=1.6.0
    - colour>=0.1.5
    - cycler>=0.10.0
    - decorator>=4.4.2
    - dtreeviz>=1.2
    - imageio>=2.9.0
    - importlib-metadata>=3.9.0
    - iniconfig>=1.1.1
    - ipykernel>=5.5.0
    - ipython>=7.16.1
    - ipython-genutils>=0.2.0
    - jedi>=0.18.0
    - joblib>=1.0.1
    - jupyter-client>=6.1.12
    - jupyter-core>=4.7.1
    - kiwisolver>=1.3.1
    - lime>=0.2.0.1
    - llvmlite>=0.36.0
    - matplotlib>=3.3.4
    - networkx>=2.5
    - numba>=0.53.1
    - numpy>=1.19.0
    - packaging>=20.9
    - pandas>=1.1.5
    - parso>=0.8.1
    - patsy>=0.5.1
    - pexpect>=4.8.0
    - pickleshare>=0.7.5
    - pillow>=8.1.2
    - pluggy>=0.13.1
    - prompt-toolkit>=3.0.18
    - ptyprocess>=0.7.0
    - py>=1.10.0
    - pydotplus>=2.0.2
    - pyexplainer>=1.1.6
    - pygments>=2.8.1
    - pyparsing>=2.4.7
    - pytest>=6.2.2
    - python-dateutil>=2.8.1
    - pytz>=2021.1
    - pywavelets>=1.1.1
    - pyzmq>=22.0.3
    - scikit-image>=0.17.2
    - scikit-learn>=0.24.1
    - scipy>=1.5.0
    - shap>=0.39.0
    - six>=1.15.0
    - sklearn>=0.0
    - slicer>=0.0.7
    - statsmodels>=0.12.2
    - threadpoolctl>=2.1.0
    - tifffile>=2020.9.3
    - toml>=0.10.2
    - tornado>=6.1
    - tqdm>=4.59.0
    - traitlets>=4.3.3
    - typing-extensions>=3.7.4.3
    - wcwidth>=0.2.5
    - xgboost>=1.4.1
    - zipp>=3.4.1
